# Site settings
title: Fusk og snusk med Jekyll
email: belowyn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
	Random musings about tech, RPGs, food and whatever.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://belowyn.github.io" # the base hostname & protocol for your site
twitter_username: belowyn
github_username:  belowyn

# Build settings
markdown: kramdown
